ALTER TABLE Participacao
ADD COLUMN IF NOT EXISTS Data_solicitacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS Mensagem_solicitacao VARCHAR(300),
ADD COLUMN IF NOT EXISTS Mensagem_resposta VARCHAR(300),
ADD COLUMN IF NOT EXISTS Data_resposta TIMESTAMP;

UPDATE Participacao
SET Status = 'PENDENTE'
WHERE Status IS NULL;

ALTER TABLE Participacao
ALTER COLUMN Status SET DEFAULT 'PENDENTE',
ALTER COLUMN Status SET NOT NULL;